### ISSUE TITLE
  java.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.Size.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by VattipalliSridhar** [mitchtabian/TabianCustomCamera#2]
06-29 15:19:34.687 19819-19869/codingwithmitch.com.tabiancustomcamera E/AndroidRuntime: FATAL EXCEPTION: CameraBackground
    Process: codingwithmitch.com.tabiancustomcamera, PID: 19819
    java.lang.NullPointerException: Attempt to invoke virtual method 'int android.util.Size.getWidth()' on a null object reference
        at codingwithmitch.com.tabiancustomcamera.Camera2Fragment.createCameraPreviewSession(Camera2Fragment.java:972)
        at codingwithmitch.com.tabiancustomcamera.Camera2Fragment.access$1900(Camera2Fragment.java:86)
        at codingwithmitch.com.tabiancustomcamera.Camera2Fragment$7.onOpened(Camera2Fragment.java:940)
        at android.hardware.camera2.impl.CameraDeviceImpl$1.run(CameraDeviceImpl.java:118)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by mitchtabian** [comment]
watch this video: https://player.vimeo.com/video/274979439
